### ISSUE TITLE
https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it

### ISSUE THREAD

**Issue by vv12131415** [adobe-webplatform/eve#33]
I can't find the previous version of the package with bower, I mean this one https://github.com/DmitryBaranovskiy/eve , could you please leave there or make an redirect to this lib from  previous repo?

**Comment by platx** [comment]
I got the same issue today when was updating composer dependencies. Can not install a project due this error. 
Error:

> [Composer\Repository\InvalidRepositoryException]                             
>   No valid bower.json was found in any branch or tag of https://github.com/Dm  
>   itryBaranovskiy/eve.git, could not load a package from it.

**Comment by zmiftah** [comment]
Any news on this? It has been a while now. I can't install package from kartik-v/yii2-widget-datepicker

**Comment by vv12131415** [comment]
@platx @zmiftah as a workaround install in with specific commit [see stackoverflow](https://stackoverflow.com/questions/21314381/how-to-correctly-require-a-specific-commit-in-composer-so-that-it-would-be-avail)

**Comment by muet84** [comment]
I have following in my composer.json and now this issue fixed. You may take out installer-paths if not required in case.

"config": {
        "fxp-asset": {
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            },
            "repositories": {
            "bower-asset/eve": {
            "type": "bower-vcs",
            "url": "https://github.com/adobe-webplatform/eve.git"
            }
          }
        },
        "process-timeout": 1800
    }

**Comment by nurbeknurjanov** [comment]
> I have following in my composer.json and now this issue fixed. You may take out installer-paths if not required in case.
> 
> "config": {
> "fxp-asset": {
> "installer-paths": {
> "npm-asset-library": "vendor/npm",
> "bower-asset-library": "vendor/bower"
> },
> "repositories": {
> "bower-asset/eve": {
> "type": "bower-vcs",
> "url": "https://github.com/adobe-webplatform/eve.git"
> }
> }
> },
> "process-timeout": 1800
> }

thank u man
