### ISSUE TITLE
npm ERR! D:\Software\git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git

### ISSUE THREAD

**Issue by darksc** [adobe-webplatform/eve#34]
npm ERR! D:\Software\git\[cmd](https://so.csdn.net/so/search?q=cmd&spm=1001.2101.3001.7020)\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git

what?

**Comment by vthwang** [comment]
I have the same issue here.
I use yarn.
Here is the error message.

```
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/adobe-webplatform/eve.git
Output:
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
```

**Comment by darksc** [comment]
> I have the same issue here. I use yarn. Here is the error message.
> 
> ```
> Exit code: 128
> Command: git
> Arguments: ls-remote --tags --heads git://github.com/adobe-webplatform/eve.git
> Output:
> fatal: remote error:
>   The unauthenticated git protocol on port 9418 is no longer supported.
> ```


https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

> Improving Git protocol security on GitHub
> We’re changing which keys are supported in SSH and removing unencrypted Git protocol. Only users connecting via SSH or git:// will be affected. If your Git remotes start with https://, nothing in this post will affect you. If you’re an SSH user, read on for the details and timeline.


fix:

> For local projects
> For all your repositories, you can set:
> 
> git config --global url."https://github.com/".insteadOf git://github.com/
